src/domain/Voicemail.js
In the desktop project, I needed to get the unread status before acknowledging it. To do so, I have just added the field in the Voicemail constructor.
=> Updated voicemail constructor to get the unread status

dist/wazo-sdk.js, package.json, src/domain/Call.js, src/domain/CallLog.js, src/domain/ChatMessage.js, src/domain/Voicemail.js, src/domain/__tests__/CallLog.test.js, src/lib/sip-0.11.1.js, src/web-rtc-client.js, webpack.config.js, yarn.lock
@see https://github.com/onsip/SIP.js/commit/f338c112f17fa51a51beeb2aedf5aed6faa5fc16#diff-f70611c8dc5355847d05b0fa20c054fd
Fix issues with `undefined is not an object (evaluating 'e.hasHeader')`.
=> Backport sipjs CRLF fix #f338c112f

src/domain/Contact.js
Getters pour emails/numbers, en prévision de supporter plusieurs courriels et numéros.
=> Getters for multiple numbers / emails

src/domain/Session.js, src/domain/__tests__/Session.test.js
=> Add session.hasExtension(extension: string) method

src/api-client.js, src/api/chatd.js, src/domain/Contact.js, src/domain/Profile.js, src/domain/__tests__/Session.test.js, src/index.js, src/websocket-client.js
=> ⚠️ Add chatd presence API

src/api/dird.js, src/domain/Contact.js
Add API methods for Google Contacts support
=> Google contacts support

src/domain/Contact.js
Given no backend from source, when parsing personal contact, use personal backend
=> Fix personal contact parsing

src/web-rtc-client.js
https://sipjs.com/api/0.13.0/register/#extracontactheaderparams
=> fix mobility header

src/api/chatd.js, src/domain/Contact.js, src/domain/Profile.js, src/domain/__tests__/Contact.test.js, src/index.js
=> Rename presence to state to avoid misunderstanding

src/domain/Contact.js
- Define default contact number
- Reorder number priority (Office 365)
=> [WDA-1149] Google and Office365 Contacts

src/domain/Phone/WebRTCPhone.js
- Current sound is a placeholder
=> [WDA-1202] Play sound on call termination

src/domain/Phone/CTIPhone.js, src/domain/Phone/WebRTCPhone.js, src/utils/Heartbeat.js, src/utils/__tests__/Heartbeat.test.js, src/utils/heartbeat.js, src/web-rtc-client.js
=> Add WebRTC heartbeat

src/utils/PhoneNumberUtil.js, src/utils/__tests__/PhoneNumberUtil.test.js
Avoid to parse number with letters ...
=> Fix displayable number

src/web-rtc-client.js
Generate an audio element in video mode (the same way we would with an audio-only call).
=> Add audio element in video-mode

src/simple/room/Room.js
We already have access to it, might as well use it.
=> Simple SDK: Set Room Name

README.md, src/domain/Phone/WebRTCPhone.js, src/web-rtc-client.js
Format update for more clarity.
=> Format update

src/domain/SipLine.js, src/simple/Phone.js
Add the ability to retrieve SFU state without throwing an error
=> Add `getSfu()`

src/api/agentd.js
Relates to [WDA-1327: Line ID agent login](https://github.com/TinxHQ/wazo-web-desktop/pull/885)
=> Agent: login with line id

src/utils/api-requester.js
See https://github.com/wazo-platform/wazo-calld/blob/master/wazo_calld/plugins/calls/http.py#L72
=> api-requester: include 201 as success status code

src/domain/Contact.js
Related to [this PR](https://github.com/TinxHQ/wazo-web-desktop/pull/869)
=> DND / Presential changes

zuul.d/pre.yaml, zuul.d/run.yaml
=> zuul: use Node 12

src/domain/SipLine.js
Fixes https://github.com/wazo-platform/wazo-js-sdk/pull/399#discussion_r488660540
=> Retrieve host from endpoint_section in PJSIP

src/lib/WazoSessionDescriptionHandler.js, src/web-rtc-client.js
Cf: https://github.com/onsip/SIP.js/blob/f11dfd584bc9788ccfc94e03034020672b738975/src/platform/web/simple-user/simple-user.ts#L588
=> Send DTMF via INFO in mobile environment

.eslintrc, src/checker/checks/ice-ipv4.js, src/checker/checks/index.js, src/checker/checks/symmetric-nat.js, src/checker/checks/webrtc-transport.js, src/domain/Contact.js, src/lib/WazoSessionDescriptionHandler.js, src/utils/webrtc.js
See https://webrtchacks.com/symmetric-nat/
=> Check form Symmetric NAT in stack checks

src/simple/Websocket.js
`Wazo.Websocket.ON_OPEN` returned `undefined`
=> Fix socket events exported

src/domain/Contact.js, src/domain/Profile.js
- adds a new PROGRESSING line state
- add a `Contact.previousPresential` property
=> [WDA-1663] Use progressing line state

src/api/calld.js, src/domain/Call.js, src/domain/CallSession.js
Complements [WP-319](https://github.com/TinxHQ/wazo-web-desktop/pull/1079)
=> Add recording and recordingPaused states and handlers

package.json, yarn.lock
See https://github.com/muaz-khan/getStats/pull/29
=> Use manuquentin's repo to get getstats fix on iOS

src/web-rtc-client.js
_Required by this [WDA PR](https://github.com/TinxHQ/wazo-web-desktop/pull/1191)_
=> Add ID to audio tag

README.md, src/api/chatd.js
=> Allow to fetch all users statuses in chatd and document it

README.md
- Fixes links in the read-me so that they all correctly jump to the relevant section
=> [WAZO-2665] Fix readme anchor jumps

README.md
- corrects a function call typo
=> fix function call in advanced API code example

src/service/IssueReporter.js, src/service/__tests__/IssueReporter.test.js
Cf: https://sentry.io/organizations/wazo/issues/3113995482/?project=1356803&query=is%3Aunresolved
=> [WDA-1971] Do not try to add _retry value on grafana string logs

.gitignore, src/api/confd.js, src/domain/Meeting.js, src/domain/MeetingAuthorization.js, src/domain/__tests__/Meeting.test.js, src/domain/__tests__/MeetingAuthorization.test.js, src/types/WebSocketMessage.js, src/utils/__tests__/object.test.js, src/utils/__tests__/string.test.js, src/utils/object.js, src/utils/string.js, src/websocket-client.js
Related pull requests:
- WDA: https://github.com/TinxHQ/wazo-web-desktop/pull/1352
- Meet: https://github.com/TinxHQ/wazo-meet/pull/15
- Common: https://github.com/TinxHQ/wazo-js-common/pull/10
=> [WP-476] Meeting Access Request

src/domain/Phone/WebRTCPhone.js, src/web-rtc-client.js
Since this API doesn't exists (yet) on react-native-webrtc.
=> Avoid to call getSenders on mobile

.travis.yml
Why:
* AFAIK this is not used anymore
=> CI: remove travis

src/api/confd.js
in  confd, meetingAuthorizations parsing response, original code not gives items as input for parser and that cause error
=> fix meeting authorizations parsing issue

README.md, package.json
=> Support webpack 5

src/domain/types.ts, src/simple/Phone.ts, src/web-rtc-client.ts
Setting no-answer timeout at 24hr, and letting actual value to be defined by the backend.
=> [WP-850] Hardcode no-answer timeout

src/web-rtc-client.ts
https://wazo-dev.atlassian.net/browse/WP-881
We need to check if a backend solution should be better.
=> Mute call when holding it

src/web-rtc-client.ts
=> [WDA-2253] Do not replace audio track after a reinvite

package.json, src/index.ts
- Should allow to import anything from lib without having to declare a path for each potential import in `exports`
=> [WP-1108] More exports from lib

src/domain/Phone/WebRTCPhone.ts
Extends https://github.com/wazo-platform/wazo-js-sdk/pull/735
=> [WDA-2282] Fix call session state when holding & resuming a previously muted call

package.json, src/domain/Incall.ts, src/domain/Line.ts, src/domain/Profile.ts, src/domain/__tests__/Profile.test.ts, src/domain/types.ts, src/index.ts
- Improve Extension typing / usage
- Add `incalls` key to user profile
=> [WDA-2371] Add incall for profile object

package.json, yarn.lock
depends-on: https://github.com/wazo-platform/getStats/pull/2
- Use latest version of getStats
=> [WP-1695] get stats

src/api-client.ts, src/api/agentd.ts, src/api/amid.ts, src/api/application.ts, src/api/auth.ts, src/api/call-logd.ts, src/api/calld.ts, src/api/chatd.ts, src/api/confd.ts, src/api/ctid-ng.ts, src/api/dird.ts, src/api/webhookd.ts, src/base-api-client.ts, src/domain/types.ts, src/types/api.ts
- Remove interface and let TypeScript export definition from codebase
- Applied missing return type on few functions
- Add empty line between all functions
------
🧙  To help review, use `hide whitespace` option 🧙
=> [WP-1763] Refactor code and remove interfaces

src/api/confd.ts, src/domain/CallLog.ts, src/types/WebSocketMessage.ts, src/types/api.ts
- Generic ListResponse Type
- Fix `getBlockNumbers` return type
=> [WP-1763] style(blocklist): wrong return type for list

src/domain/Session.ts
This is a breaking change, bump version accordingly following merge
=> Remove engineUuid from Session toJSON method

src/web-rtc-client.ts
mechanism for ICE reconnection attempts, ensuring graceful handling of connection failures.
* **Added retry mechanism for ICE reconnection attempts:**
- Introduced a constant `MAX_ICE_RECONNECT_ATTEMPTS` to define the maximum number of reconnection attempts.
- Added a new property `iceReconnectAttempts` to track reconnection attempts for each session. [[1]](diffhunk://#diff-4c395fa3062a6f6cec6a08bc0cee2f1e61d5015cbaf39e896ee2976ea203e216R129-R130) [[2]](diffhunk://#diff-4c395fa3062a6f6cec6a08bc0cee2f1e61d5015cbaf39e896ee2976ea203e216R222)
- Implemented logic to attempt ICE reconnection up to the defined limit, with appropriate logging for each attempt and failure scenarios.
* **Session cleanup improvements:**
- Enhanced the `onCallEnded` method to delete `iceReconnectAttempts` for the …
=> [WDA-2308] Ice connection retries
