wazo-platform/wazo-js-sdk

src/api/dird.js

Change DIRD api call payload.
- Use sourceId to identify the personal contact to update.
- Default values to empty strings because the backend service won't allow null values.

Change DIRD payload

---

src/domain/Voicemail.js
src/domain/__tests__/Voicemail.test.js

The backend return `timestamp: 1530823017` for example, and it is actually a unix timestamp. The expected value is `// Thu Jul 05 2018 16:36:57 GMT-0400 (GMT-04:00)`, but without the fix it returns `Jan 17 1980`

Bug fixes/voicemail in millis

---

src/domain/CallLog.js

J'ai changer la façon que les call log determine la direction. Maintenant au lieu de vérifier si c'est leur numéro primaire, il vérifie s'il s'agit d'une de ses lignes.

Update call log direction mechanism

---

src/utils/PhoneNumberUtil.js
src/utils/__tests__/PhoneNumberUtil.test.js

Pair-programming session with @manuquentin. 
@sboily when we use libphonenumber on an unformatted number we got an exception, hence the use of regexp.
Could you give us more insights into what are the expected behaviour?

add support for phone number without country code

---

.hooks4git.ini
README-dev.md

I want to add the following to https://github.com/tinxhq/wazo-notebook-private/git-hooks.md
---
> Auto checks your code before you ship it. Works with any programmning language.
**requirements:** [`pip`](https://packaging.python.org/guides/installing-using-linux-tools/#installing-pip-setuptools-wheel-with-linux-package-managers)
pip install hooks4git --user
cd working-project/
hooks4git --init
Now you get a new `.hooks4git.ini` and some hooks in `.git/hooks`

add basic hooks4git config to run test and format before push

---

src/domain/Contact.js

Maintenant, on va lire dans les deux colonnes pour determiner le numero plutot que de renvoyer des nulls

Fix missing number when parsing favorites

---

src/domain/Contact.js
src/domain/__tests__/Contact.test.js

Check that backend exists and is the same for both contacts when comparing via `Contact.is`

Add backend comparison to Contact.is

---

src/api/dird.js
src/domain/Contact.js

While parsing conference contacts, verify that you have extensions before accessing first value

Fix conference parsing

---

src/domain/Contact.js

Handle the case where the `sourceId` returned by `https://quintana.wazo.community/0.1/backends/conference/sources/{source_uuid}/contacts` is a number instead of string

Convert numerical sourceId to string when parsing conference contacts

---

src/api/confd.js
src/domain/Session.js
src/domain/__tests__/Session.test.js

- Add route to get infos about Wazo engine
- Update `Session.primaryContext` to add logic according to Wazo engine version

confd -> get infos

---

src/domain/Contact.js
src/domain/Session.js
src/domain/__tests__/Session.test.js
src/utils/__tests__/compare-version.test.js
src/utils/compare-version.js
yarn.lock

⚠️
```js
Number('19.10') === Number('19.1')
```
We should have a real way to compare engine version, instead of comparing version casted in float.

Fix the way engine versions are compared

---

.flowconfig
README.md
package.json
src/__tests__/api-client.test.js
src/api-client.js
src/api/accessd.js
src/api/application.js
src/api/auth.js
src/api/call-logd.js
src/api/calld.js
src/api/chatd.js
src/api/confd.js
src/api/ctid-ng.js
src/api/dird.js
src/domain/Phone/CTIPhone.js
src/domain/Session.js
src/domain/__tests__/Session.test.js
src/service/CallApi.js
src/service/getApiClient.js
src/utils/__tests__/api-requester.test.js
src/utils/api-requester.js
src/web-rtc-client.js
src/websocket-client.js
yarn.lock

⚠️ Breaking change: API methods don't take a token as first parameter anymore.
```js
const client = new WazoApiClient({ server: ..., clientId: 'myClientId' });
const { refreshToken, token, uuid } = await client.auth.logIn({ username: '...', password: '...', expiration: 3 });
client.setToken(token);
client.setRefreshToken(refreshToken);
await new Promise(resolve => setTimeout(resolve, 5000));
const senderId = await client.auth.getPushNotificationSenderId(uuid);
console.log('senderId', senderId);
```

Add refresh token mechanism

---

src/domain/Contact.js

Backend now returns an array of objects:
```
[
{
'address': 'a1@wazo.io',
'label': 'address1'
}
]
```

[WDA-1177] Google integration: use new e-mail field format

---

src/domain/Phone/WebRTCPhone.js

No need to play hangup sound in `phone.endCurrentCall` as `phone.  _onCallTerminated` already covers it -- and more

[WDA-1202] Fix play sound on call termination

---

zuul.d/pre.yaml
zuul.yaml

Why:
* When Debian updates their repo, we need to fetch the latest version of
packages
* Else, we may get an error like
E: Failed to fetch
http://deb.debian.org/debian/pool/main/n/nodejs/libnode64_10.19.0~dfsg1-1_amd64.deb
404  Not Found [IP: 199.232.36.204 80]

zuul: fix installation of yarn

---

src/domain/Phone/WebRTCPhone.js

`_createCallSession` gets `startTimer` from another `callSession`, otherwise it generates a new one.

Fix timer reset on hold

---

src/domain/Phone/WebRTCPhone.js

For some reason, that `null` generates a `CallSession.callId = null`, which was ultimately throwing a monkey wrench into the switchboard's indirect transfer process.

Prevent a null CallSession callId

---

src/web-rtc-client.js

Takes care of this corner case:
- Bob video-calls Alice
- Alice answers in audio
- Alice holds Bob, and comes back
- Alice hangs up; fails -- gotta hangup again from the banner

[WDA-1403] Fix hangup on audio-answered video calls

---

src/domain/Phone/WebRTCPhone.js
src/web-rtc-client.js

We have to renegociate ice after losing the connection.
Was OK in 0.36.x but not since the big refactoring in 0.37.x

Fix missing iceRestart when losing connection

---

src/api/auth.js

- the `tenant_id` field can be provided at log in

[WAZO-2696] Support tenant_id field at token creation

---

README.md
src/api/auth.js
src/simple/Auth.js
src/simple/index.js

- `backend` and `tenantId` can now be provided when using the simple API to log in
- introduces backend constants in Auth class

[WAZO-2697] Add simple api login ldap support

---

src/domain/Phone/WebRTCPhone.js

Situation: 
- Alice is in a  video call, 1:1: or conference
- Alice shares her screen
- Alice puts the call on hold while screensharing
- Alice resumes the call, which prompts screen/window selection
- Alice shares her screen again
- Alice stops the screen sharing
Bug
- Alice is in an audio call
Expected result
- Alice should be in a video call

[WDA-1966] Fix video following a held screensharing session

---

README.md
src/domain/__tests__/Line.test.js
src/simple/Softphone.js

Heads up: throwing an error in `simple/Softphone.js` as opposed to defaulting to `stack.dev` -- not sure this is the appropriate way to handle this.

Remove stack.dev.wazo.io references

---

README.md
src/__tests__/web-rtc-client.test.js
src/domain/Phone/WebRTCPhone.js
src/web-rtc-client.js

**Summary of changes**
- Adds a `force` param to change the audio input device in cases where the device has changed but has the same `id` than before (e.g user unplugs a microphone with id `default` and OS fallbacks to a new default microphone and is given id `default`).

[WDA-1981] add force param for WebRTC changeAudioInputDevice

---

src/__tests__/web-rtc-client.test.js
src/web-rtc-client.js

**Summary of changes**
- to perform a track change, the actual `deviceId` of the default device is used. If it cannot be found, `default` will be used.
- fix flow

[WDA-1981] Handle default device to new default device track change

---

src/web-rtc-client.ts

`reject`, `cancel` and `bye` are async. So we need to await them to be able to fall in the catch block.

Await for hangup actions to let the try/catch block do its job

---

README.md
src/api/dird.ts
src/domain/Contact.ts
src/domain/__tests__/Contact.test.ts

- Makes it possible to limit the number of results returned by the contact search. The backend does not support a `limit` parameter yet, but we can handle it on the front end until that feature is available.

[WDA-1972] Introduce limit param for dird contact search

---

src/service/IssueReporter.ts
src/service/__tests__/IssueReporter.test.ts

To avoid hammering unstable fluentd, changed retry algorithm to use exponential backoff with random jitter.

Exponential backoff for fluentd log shipping

---

src/domain/Phone/WebRTCPhone.ts

- We might sometimes receive an audio track with `enabled` set to `true`. We don't want to stop that audio track when stopping screensharing so we should ensure the track we stop is of the video kind.

Only stop video tracks when stopping screenshare

---

.eslintrc
src/simple/Phone.ts
src/web-rtc-client.ts

Why ?
Logger is only activated when creating the user agent.
So we have to register again when enabling log.

Add enable logger in webRtcClient

---

src/domain/Session.ts

Make `expiresAt` valid is major browsers. Currently when parsing `utc_expires_at` the output in Firefox or Safari is `Invalid Date`. Since we already have `moment` we should use it to parse API response to a Javascript date

[NES-2220] expiresAt valid in major browsers

---

src/__tests__/api-client.test.ts
src/api/auth.ts
src/simple/Auth.ts
src/simple/__tests__/Auth.test.ts
src/simple/index.ts

- add a method to obtain the `location` and `saml_session_id` from the wazo-auth `saml/sso` route

[WDA-2366] [WDA-2367] Initiate idp login (SAML)

---

src/utils/__tests__/api-requester.test.ts
src/utils/api-requester.ts

- Some characters that exceed 1 byte such as `€` would cause the function to throw

[WP-1177] handle special characters in base64Encode

---

src/api/auth.ts
src/simple/Auth.ts
src/simple/__tests__/Auth.test.ts

- let the api-requester parse the response
- rely on status from BadResponse or ServerError

SAML error handling refactor

---

src/web-rtc-client.ts

- We cannot use `wss` as it does not respect the RFC and can cause undesired side effects

[WDA-2463] Do not use wss in user agent

---

src/domain/CallLog.ts
src/domain/Session.ts
src/domain/__tests__/CallLog.test.ts

Introduction new method `isIncomingAndForwarded` for a call log item
Since `24.14`, call log items are more robust about `requested` and `destination` field value
- `requested` will always be the first extension/contact the `source` tried to reach
- `destination` will always be the last extension/contact reached in a call «glow»

[WDA-2380] Mark incoming call as forwarded

---

src/domain/CallLog.ts
src/domain/__tests__/CallLog.test.ts

Since API always gives `user_uuid` we should check again this value. Line extension can be changed overtime, but not UUID
Ref Backend Change: https://github.com/wazo-platform/wazo-call-logd/pull/242

[WDA-2380] Internal CallLog, also check current user uuid for direction

---

README.md
src/api-client.ts
src/base-api-client.ts
src/constants.ts
src/index.ts
src/service/__tests__/getApiclient.test.ts
src/service/getApiClient.ts
src/utils/api-requester.ts

`wazo-js-sdk` is very useful for end-user's applications type. But when building an admin application for example, we do not include all admin APIs. So developers needs to use two set of codebase to handle this use case.
We have API Requesters, but this also force developers to loop to each API Requester and initialiser to handle `refreshTokenCallback` mecanism.
- Extract `BaseApiClient` class
- `WazoApiClient` now depends on BaseApiClient
- `getApiClient` now accept new parameter for custom ApiClient

[WAZO-4003] Allow extend api client

---

src/api/confd.ts
src/domain/types.ts
src/types/api.ts

depends-on: https://github.com/wazo-platform/wazo-js-sdk/pull/807
depends-on: https://github.com/wazo-platform/wazo-confd/pull/507
- Add generic type for Api QueryString Params
- Add blocklist number api, base on spec

[WP-1763] blocklist api

---

jest.config.js
src/api/call-logd.ts
src/domain/CallLog.ts
src/domain/__tests__/CallLog.test.ts

- Add the new `call_status` field in CallLog domain
- Allow to pass extra query params when listing call logs.

[WAZO-4164] CDR `call_status` and improve listing query params

---

package.json
pnpm-lock.yaml

- Use latest types
- Use latest required of node (now match wazo-js-sdk)

build: use types from 25.08 + node requirements
